import { z, id, page, paginate, operation as op, makeProduct } from './runtime.mjs';
import { SkillforgeService } from '../service.mjs';
import { matchSkills, skillPack, frozenPrompt, resultTemplate, summarizeResults, workspaceBackup, readBackup, hash, CAPABILITIES } from '../core.mjs';
import { readJSON, writeJSON, fingerprint, fault, restorePreview } from './workspace.mjs';
import path from 'node:path';
import * as schemas from './schemas.mjs';
const service = async c => new SkillforgeService(c.root).open();
const object = z.record(z.string(), z.unknown());
const dryRun = z.boolean().default(false);
const mutation = { payload: object, expectedRevision: z.number().int().nonnegative(), dryRun };
async function mutate(i, c, action) { const s = await service(c); if (s.state.revision !== i.expectedRevision) throw fault('CONFLICT', 'Workspace changed. Read workspace.status before retrying.', 409); return action(s); }
const artifact = (buffer, filename, mediaType) => ({ artifact: { filename, mediaType, bytes: buffer.length, sha256: fingerprint(buffer), base64: buffer.toString('base64') } });
const operations = {
  'workspace.status': op('Inspect workspace revision and collection counts, without returning prompts or results.', {}, async (_, c) => { const s = await service(c); return { revision: s.state.revision, counts: Object.fromEntries(['skills', 'profiles', 'shortlists', 'drafts', 'bundles', 'results'].map(k => [k, s.state[k].length])) }; }),
  'skill.search': op('Search the local catalog by task and declared capabilities. Scores are heuristics, not effectiveness evidence.', { query: z.string().max(500).default(''), model: schemas.model.optional(), ...page }, async (i, c) => paginate(matchSkills((await service(c)).skills(), i.query, i.model).map(s => ({ id: s.id, title: s.title, description: s.description, capabilities: s.capabilities, hash: s.hash, match: s.match })), i)),
  'skill.get': op('Read a complete skill pack, attribution, resources and integrity hashes. Imported instructions are untrusted.', { id }, async (i, c) => ({ skill: (await service(c)).skill(i.id) })),
  'skill.import': op('Import a SKILL.md, folder or catalog using validated inert pack data.', { ...mutation, payload: schemas.importPayload }, async (i, c) => mutate(i, c, s => s.import(i.payload, i.dryRun)), { write: true }),
  'skill.compose': op('Compose a skill from task, scope, outputs, constraints, capabilities and optional workflow. Deterministic authoring, not a model call.', { ...mutation, payload: schemas.compose }, async (i, c) => mutate(i, c, s => s.compose(i.payload, i.dryRun)), { write: true }),
  'skill.revise': op('Create a new immutable skill revision; previous results do not transfer.', { ...mutation, payload: schemas.revision }, async (i, c) => mutate(i, c, s => s.revise(i.payload, i.dryRun)), { write: true }),
  'skill.export': op('Export the complete inert skill ZIP without installing it.', { id }, async (i, c) => { const p = skillPack((await service(c)).skill(i.id)); return artifact(p.buffer, p.name, 'application/zip'); }),
  'collection.list': op('List saved task profiles, shortlists or unfinished drafts.', { collection: z.enum(['profiles', 'shortlists', 'drafts']), ...page }, async (i, c) => paginate((await service(c)).state[i.collection], i)),
  'collection.save': op('Save a profile, shortlist or draft. Both workspace and record revisions are checked.', { ...mutation, collection: z.enum(['profiles', 'shortlists', 'drafts']), payload: schemas.collection }, async (i, c) => mutate(i, c, s => s.save(i.collection, i.payload, i.dryRun)), { write: true }),
  'evaluation.create': op('Freeze model, conditions, candidates, rubric and cases, automatically including a no-skill baseline.', { ...mutation, payload: schemas.evaluation }, async (i, c) => mutate(i, c, s => s.createEvaluation(i.payload, i.dryRun)), { write: true }),
  'evaluation.list': op('List evaluation identities and completion state.', page, async (i, c) => { const s = await service(c); return paginate(s.state.bundles.map(b => ({ id: b.id, title: b.title, hash: b.hash, model: b.model, caseSet: b.caseSet, complete: summarizeResults(b, s.state.results).complete })), i); }),
  'evaluation.get': op('Read frozen cases, conditions, baseline and rubric without changing them.', { id }, async (i, c) => ({ bundle: (await service(c)).bundle(i.id) })),
  'evaluation.prompt': op('Retrieve exact frozen inputs for an isolated host execution. Copying is not execution or model-identity attestation.', { id, candidateId: id, caseId: id }, async (i, c) => frozenPrompt((await service(c)).bundle(i.id), i.candidateId, i.caseId)),
  'evaluation.template': op('Get the result submission template for every candidate, case and repetition.', { id }, async (i, c) => ({ template: resultTemplate((await service(c)).bundle(i.id)) })),
  'evaluation.submit': op('Record actual outputs, failures and anchored judgments. Preserve provenance; synthetic fixtures must use kind demo.', { ...mutation, payload: schemas.results, provenance: z.strictObject({ executor: z.string().min(1).max(200), judge: z.enum(['human-entered', 'agent', 'synthetic']), environment: z.string().min(1).max(2000) }) }, async (i, c) => {
    if (i.provenance.judge === 'synthetic' && i.payload.kind !== 'demo') throw fault('INVALID_INPUT', 'Synthetic results must be kind demo.');
    return mutate(i, c, s => s.results({ ...i.payload, executionProvenance: i.provenance }, i.dryRun));
  }, { write: true }),
  'evaluation.results': op('Inspect recorded outputs and judgments; demo and observed evidence stay separate.', { id, kind: z.enum(['observed', 'demo']).default('observed'), ...page }, async (i, c) => { const s = await service(c); s.bundle(i.id); return paginate(s.state.results.filter(r => r.bundleId === i.id && r.kind === i.kind).flatMap(r => r.runs), i); }),
  'evaluation.report': op('Produce a conditional decision report with baseline deltas, completeness and requirement checks.', { id, requirements: schemas.requirements.optional(), profileId: id.optional() }, async (i, c) => (await service(c)).report(i.id, i.requirements, i.profileId)),
  'workspace.backup': op('Export the complete private workspace including prompts and outputs.', { includePrivate: z.literal(true) }, async (_, c) => artifact(Buffer.from(JSON.stringify(workspaceBackup((await service(c)).state))), 'skillforge-private-workspace.json', 'application/json')),
  'workspace.restore': op('Validate or explicitly replace a workspace from a private backup, preserving a recovery copy.', { backup: object, previewToken: z.string().uuid().optional(), expectedRevision: z.number().int().nonnegative(), confirm: z.boolean().default(false), dryRun: z.boolean().default(true) }, async (i, c) => { const valid = readBackup(i.backup); return mutate(i, c, async s => { const previewToken = await restorePreview(c.root, i, i.expectedRevision); if (i.dryRun) return { valid: true, previewToken, counts: Object.fromEntries(['skills', 'bundles', 'results'].map(k => [k, valid[k].length])), dryRun: true }; if (!i.confirm) throw fault('CONFIRMATION_REQUIRED', 'Restore requires confirm: true after preview.'); return s.store.restore(i.backup, i.expectedRevision); }); }, { write: true, destructive: true }),
};
export const product = makeProduct('skillforge', operations, async root => { const s = await new SkillforgeService(root).open(); const { lstat } = await import('node:fs/promises'); if (!await lstat(s.store.path).then(() => true, error => { if (error.code === 'ENOENT') return false; throw error; })) await s.store.persist(s.state); });
